content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    filename: "{year}-{month}-{day}-{primary}.md"
    extension: md
    fields:
      - name: title
        label: Title
        type: string
        description: "The title of the blog post."
        required: true
      - name: pubDate
        label: Publication Date
        type: date
        description: "The date when the blog post was published."
      - name: tags
        label: Tags
        type: string
        description: "A list of tags associated with the blog post. Use kebab-case."
        list: true
        pattern:
          regex: "^[a-z0-9]+(?:-[a-z0-9]+)*$"
          message: "Use lower case and kebab case for tags: e.g. 'my-tag'. Not 'My Tag' or 'myTag'."
      - name: socialDescription
        label: Social Description
        type: string
        description: "A short description for social media platforms. Max 155 characters."
      - name: image
        label: Image
        type: image
        description: "An optional URL to the image for the blog post."
      - name: featured
        label: Featured Post
        type: boolean
        description: "Flag to indicate if the blog post is featured."
      - name: body
        label: Body
    view:
      fields: [title, pubDate]
      primary: title
      sort: [pubDate, title]
      default:
        sort: pubDate
        order: desc
