media:
  input: src/images
  output: /images

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    filename: "{year}-{month}-{day}-{primary}.md"
    fields:
      - name: title
        label: Title
        type: string
        description: "The title of the blog post."
        required: true
      - name: pubDate
        label: Publication Date
        type: date
        description: "The date when the blog post was published."
        required: true
        options:
          time: true
          format: yyyy-MM-dd'T'HH:mm:ss'Z'
      - name: tags
        label: Tags
        type: string
        description: "A list of tags associated with the blog post. Use kebab-case."
        list: true
        pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*$
      - name: socialDescription
        label: Social Description
        type: string
        description: "A short description for social media platforms. Max 155 characters."
        options:
          maxlength: 155
      - name: image
        label: Image
        type: image
        description: "An optional URL to the image for the blog post."
        options:
          input: src/images
          output: /images
          path: src/images
      - name: featured
        label: Featured Post
        type: boolean
        description: "Show post on frontpage"
      - name: body
        label: Body
        type: rich-text
    view:
      fields: [title, pubDate]
      primary: title
      sort: [pubDate, title]
      default:
        sort: pubDate
        order: desc
  
  - name: stuff-coding
    label: Coding Stuff
    type: file
    path: src/content/stuff/coding.json
    format: json
    fields:
      - name: content
        label: Coding Items
        type: code
        description: "Array of coding-related items"
        options:
          language: json
          
  - name: stuff-hobbies
    label: Hobbies Stuff
    type: file
    path: src/content/stuff/hobbies.json
    format: json
    fields:
      - name: content
        label: Hobby Items
        type: code
        description: "Array of hobby-related items"
        options:
          language: json
