content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    filename: "{year}-{month}-{day}-{primary}.md"
    fields:
      - name: title
        label: Title
        type: string
        description: "The title of the blog post."
        required: true
      - name: pubDate
        label: Publication Date
        type: date
        description: "The date when the blog post was published."
        options:
          time: true
          format: YYYY-MM-DDTHH:mm:ss.SSSZ
      - name: tags
        label: Tags
        type: string
        description: "A list of tags associated with the blog post. Use kebab-case."
        list: true
        pattern: ^[a-z0-9]+(?:-[a-z0-9]+)*$
      - name: socialDescription
        label: Social Description
        type: string
        description: "A short description for social media platforms. Max 155 characters."
        options:
          maxlength: 155
      # - name: image
      #   label: Image
      #   type: image
      #   description: "An optional URL to the image for the blog post."
      #   options:
      #     input: src/images
      #     output: images
      #     path: src/images
      - name: featured
        label: Featured Post
        type: boolean
        description: "Show post on frontpage"
      - name: body
        label: Body
        type: rich-text
    view:
      fields: [title, pubDate]
      primary: title
      sort: [pubDate, title]
      default:
        sort: pubDate
        order: desc

  - name: stuff
    label: Stuff
    type: file
    path: src/content/stuff
    files:
      - name: coding
        label: Coding Projects
        fields:
          - name: name
            label: Project Name
            type: string
          - name: url
            label: Project URL
            type: string
          - name: description
            label: Description
            type: text

      - name: hobbies
        label: Hobbies
        fields:
          - name: name
            label: Hobby Name
            type: string
          - name: description
            label: Description
            type: text

    # Configure how the collections are to be viewed within the CMS
    view:
      fields: [name] # List the fields you want to be displayed in the CMS collection list
      primary: name # Specify the primary field for identification
      sort: [name] # Specify the default sort order
      default:
        sort: name
        order: asc
