[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/feed.xml"
  to = "/rss.xml"
  status = 301

# [[plugins]]
# package = "netlify-plugin-rss"
#   [plugins.inputs]
#   # required configs, customize as needed
#   dirToScan = "/blog" # a subfolder to scan. "/" to scan all
#   authorName = "Ed Johnson-Williams"
#   site_url = "https://edjohnsonwilliams.co.uk"
#   title = "Ed Johnson-Williams"
#   rssDescription = "Ed Johnson-Williams' website"
#   categories = []

#   language = "en"
#   pubDate = "new Date().toUTCString(),"

  # # cheerio selectors for extractMetadataFromFile
  # # defaults shown
  # contentSelector = ".e-content"
  # descriptionSelector = "meta[name=description]" # probably no need to change
  # titleSelector = "title" # probably no need to change

  # # developer configs
  # debugMode = false # (for development) turn true for extra diagnostic logging