onlyBuiltDependencies:
  - sharp
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.1
  vite-plus: 0.2.1
overrides:
  vite: "catalog:"
  "newmd>zod": "^4.4.3"
  "newmd>zod-empty": "^2.1.0"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
